spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

#====================================mybatis-plus config===============================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.github.iphase2.accountbiz.eo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
level:
 root:
   com.github.iphase2.*.mapper: debug