spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

#====================================mybatis-plus config===============================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.github.iphase2.orderbiz.eo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
level:
  root:
    com.github.iphase2.*.mapper: debug

#=========================== seata ==============================================
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  application-id: order-service
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    # grouplist:
    #   - default
  data-source-proxy-mode: AT
  config:
    type: nacos
    nacos:
      server-addr: ${nacos-server}
      group: ${nacos-group}
      namespace: ${nacos-namespace}
      username: ${nacos-username}
      password: ${nacos-pwd}
      data-id: seata-server
  registry:
    type: nacos
    nacos:
      server-addr: ${nacos-server}
      username: ${nacos-username}
      password: ${nacos-pwd}
      #seata分组名称SEATA_GROUP
      group: ${nacos-group}
      #nacos命名空间ID
      namespace: ${nacos-namespace}
      #seata服务名
      application: seata-server

